create table if not exists public.startmed_funnel_events (
  id bigint generated by default as identity primary key,
  lead_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint startmed_event_type_length check (char_length(event_type) between 1 and 80)
);

alter table public.startmed_funnel_events enable row level security;

revoke all on table public.startmed_funnel_events from anon, authenticated;
revoke all on sequence public.startmed_funnel_events_id_seq from anon, authenticated;

grant insert on table public.startmed_funnel_events to anon, authenticated;
grant usage, select on sequence public.startmed_funnel_events_id_seq to anon, authenticated;
grant select on table public.startmed_funnel_events to authenticated;

drop policy if exists "Public can submit StartMed funnel events" on public.startmed_funnel_events;
create policy "Public can submit StartMed funnel events"
on public.startmed_funnel_events
for insert
to anon, authenticated
with check (
  event_type in (
    'lead_created',
    'quiz_completed',
    'presentation_requested',
    'meeting_requested',
    'lead_not_interested'
  )
  and jsonb_typeof(payload) = 'object'
  and octet_length(payload::text) <= 16000
);

drop policy if exists "Authenticated team reads StartMed events" on public.startmed_funnel_events;
create policy "Authenticated team reads StartMed events"
on public.startmed_funnel_events
for select
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'team'));

create index if not exists startmed_funnel_events_lead_created_idx
on public.startmed_funnel_events (lead_id, created_at);

create index if not exists startmed_funnel_events_created_idx
on public.startmed_funnel_events (created_at desc);
